---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgA22l/QVqaENEteN6ctlqssUCxVYy1Xh+wT1qImvXo6Z45OgxqQF68sVwAVQOziJ/sKxSu1NuqG1akvgkOUIIwPC2xW0o9lS/aavQWriihG0xMAYinIhiSOfY3J+LRygD0zsDsKxtHAP3REAx09vG6m1X4SePoj+vCEcFgPGuVOF4KGw8VO33AW0bYWkvOiy+ya5/0dtvw0kWBG0Ku7iaSfLdEWgSq59eKCtRR1gh6q7TYlj/IRg/HCtkX/eK8cBR9KG3u+yVgmUJHBPXCpT1OLV9Bww8PuYbhJaKvOzrbNnAEQ72n7OFCBOboozbRwzQDOUPtdsLKQD9mN9AHP0qxNk6XwWcfZuyYqSRp3T8ArMx0i4RBdLlPk48zjz50A+aLyEUdYBst0VUoLgAdSGE6FqzdcJg7WqrR/WzAXK2tGuY93NG8RrnfuuRysVQ2f76blOqP55GoYoJv9FfdUsAqG4vNeWoylXrjbyu4ygIMgkv6XuDrG9GtNeXX/aBLY5/Gt0gE/6owUKqG2HoIXIZIlfzduBlKqpLcSqhumP+XcmuR3CfBeu24SqLR8bHASqXHTJVgtL/pRIN5s2c9HFpUpulCJ31wJxXowav55xIyTZ4Nbqe7WjbS89nK60oVj/XmoQGPP/fYSX6wa7ZFjfW3YHXzzF+/Jatmzw+fpFCANLdC2IKTZILoUfnHGvGoWWN70+kgLcPn/P9I+IsCQTHT1dKfQWUbL87HvNZe6hLUfT1XquvUfsdKHzFy63JBLbP+NoMi41ESxlNZ1Iag7tQ97RxcYPnEM/NiFUqLWU1fIOES4SSoRVypV2vazSbI8/NGlJEnJjZZDUCx7vn2gqJC4/vwnBfcFjiyeS1U/3h1zJl03+4Dn7lsLcxIpXY+76nuYPZBCS3Y/rv3SXszNcp6YnM/liW1zE0AQhPQx0Qh2eHgtJQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-secret
      namespace: cloudflare
