---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAfPvywHEKIix4vl6IwMz5SJKE+YWjqpRjjUy0f1NegsH5ImPcZ0iNN4A2jF9N0dDDaRP4qVUFAVXtFjxqHKOkcN0+VhJqYAZ/wekhe2Ls1u/0+1t7qHD5a/zgrzisiOK3a0xB4V9JjdQsBOd7bIdxVhRVfLO1BFokOi0mcON+HGvBnd/b6x6Q9cdOcQQ168vs+sOMof4imIVrQhS9tHIZuNs+mjCq/1XosRK9KuwazouLMuFjlIAryAzeQVehCWbAf490NuQ9tQwF42xFVea5asSvzRs1+LeYxnqjqBUePfKyINNKPK69KI8XpduxV6jVCy2OzwDVZtvj2NZisENEAtHK3+UAbpUjRmd16FqNiA6E0sJzP45WpGzy8/JO03JHoycTtwuFlq3Jp/gigfNrvjTffA7AnXBkpwyEYTLnY1FQF5gwcgmumhLFLv6n31ZQvE+AQu9l/LFDjAYSOMLgBEetFamZVEO1PAXB8kyXBEkm07d1GSLFGJLcLwTVeOH+no9IBdOGTpNN3KRUvtDWQl4XjjCDOLviCSJKCXTcAaoJmeQHfqf/mOx7A/aAQGDmsy1/XUkaAe1Z2SZj+0wiiCGwFZbv+AOTZU0TFpCPctgwaRaN96Ji/x+707Yk3WAV+4nw3LrqVOOC+1VzxPO2ohPniqmCwHQNN4TdKuGUTpe75zVQ8mLPgKbVAdv/RWP8IohUod/S1CFdEktGC2hrHerWDMHn8Pe//M2j7njjX5egANDE+L+G+8Z3xfycyct72rut7Croc19cfmKa4YFHlWLVm4jvJrzPN2jt4CHp5AK2gqO2axRpwVcp/MwpzLIBRVlAWSfKdmv7UaKBvHulFJwLAjNbEaIhLvu8ZdHWBan6ryw/FQT37+9DDFv+ZptEqsSPl2Jnb1YqPkF3YnKaNoluQQiADyiR6XukvwgPWI1yHI4c=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-secret
      namespace: cloudflare
