---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAJh0CMCbA8k6AKGCG8ejB/KYu03bkZ11IxK6bhMFwIoCNrIN22V7wV+8kaHPpeQdjIo14QxTtmSSabu3vKDHAzJI5PHvfN+Fg/fBdY4BsfWTBdt9J1TJ2TQqG8LeTN3mzqBTslJ9tzSkxFT0VjJdd2T9fMFFw3yHV/rB8xe5O4RWGgN0Kv7bBiJd7sy513oKittPiKGQwrvlqBgYaqKpChOEtWVjjuERT3zuzr4I0o23MTIE/GFH7h3UQHvbLmL1nt1uUKDtyx7B6oTsculTE3noig/lH89kRbqWgBgOLEE51mFs2bn/1XsD5rB1yq3i+26RPmjDoWZrISxZNAwYNHqBRJ9TcAJvuptlzhljTN5Z6jRBasFCVpLPmZ2efW9q3tVLX1jfjmpSBHnztmZhPE1QXkaiO6vIBp5qPCmcmzDVNoSjZM0jbtoo0RuXf4reZEvF88VVEnTZpDOL/BBFmYiqEbrmB1l28L6lSTMdUIIrAKdQPribPWxktuMAqSno3KO4yhJxpJOt1ZO3gQhvmEZuRm/iMY/8dTiwIwtb35kBPZ6DFLnijVV5FFGDD0QrjFmIMB4uQQK/K0MvJsir5CLE/gKqxQE6LprgpLKttsVogHR5K+g9eZnGJFJi9tOVzUmwkWvCGEQ6MSQpMsgyIiYF2jofm86vYZsv1cq8ib5BVMHIfXJpUuZA3dcUcVi8ZdyYxGEqpU0IaVLdb2x/jILfirPeiBEGSK/DIbCxxu1BDZJ/WkTHe6yA3SFRKt3oqo8IJpT7LbvxCglrDnRCzZr2aI99wY1e3HlnSt0KXJgZpEsXG3D7blARptX5LtHq5zatLjx6BN2I6Za3eResCNDwLhNckRuAYfZYz86ZCLEDuwb5Qi+tMuzmw2p6yLjNWizV4p+1O5FeI/0C/oLvSWljae/audb1AUGIMEpD85vg9Y1g==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-secret
      namespace: cloudflare
