apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: cloudflare-tunnel-secret
  onlyMappedSecrets: true
  map:
    - bwSecretId: e408ebeb-ba6e-4def-b1a7-b48f00e7bbb6
      secretKeyName: credentials.json
  authToken:
    secretName: bw-auth-token
    secretKey: token
