apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

resources:
  - ../base
  - cloudflare-tunnel-secret.yaml

helmCharts:
  - name: cloudflare-tunnel
    repo: https://cloudflare.github.io/helm-charts
    version: 0.3.2
    releaseName: bingops
    valuesFile: values.yaml
    namespace: cloudflare
