cloudflare:
  tunnelName: "bingops-tunnel"
  secretName: "cloudflare-tunnel-secret"

  ingress:
    - hostname: www.bingops.com
      service: http://portfolio.bingops.svc.cluster.local:80
    - hostname: bingops.com
      service: http://portfolio.bingops.svc.cluster.local:80
    - hostname: blog.bingops.com
      service: http://blog.bingops.svc.cluster.local:80

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
