apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: authentik-secrets
  onlyMappedSecrets: true
  map:
    - bwSecretId: 9f9a140e-54c3-48dc-9aa9-b48f00e7e40b
      secretKeyName: AUTHENTIK_ARGOCD_PROD_CLIENT_SECRET
    - bwSecretId: adc3578c-4d92-4958-863b-b48f00e7e49c
      secretKeyName: AUTHENTIK_ARGOCD_TEST_CLIENT_SECRET
    - bwSecretId: ef0d29b9-60fb-4f38-814b-b48f00e7e52e
      secretKeyName: AUTHENTIK_BOOTSTRAP_EMAIL
    - bwSecretId: 3284e47b-9161-4cf2-b14c-b48f00e7e5be
      secretKeyName: AUTHENTIK_BOOTSTRAP_PASSWORD
    - bwSecretId: 85c73cb5-9032-468a-98f1-b48f00e7e653
      secretKeyName: AUTHENTIK_POSTGRESQL__PASSWORD
    - bwSecretId: cc00d39c-f552-40f3-a0ba-b48f00e7e6e7
      secretKeyName: AUTHENTIK_SECRET_KEY
    - bwSecretId: 354ff14f-5125-4933-9d5c-b48f00e7e77c
      secretKeyName: password
    - bwSecretId: b80ef121-15a8-443d-9e42-b48f00e7e807
      secretKeyName: postgres-password
    - bwSecretId: 033cdfad-0844-4c2b-ba6d-b48f00e7e89e
      secretKeyName: replication-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
