apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  argocd.yaml: |
    version: 1
    metadata:
      name: argocd-oidc
    entries:
      - model: authentik_core.group
        identifiers:
          name: argocd-admins
        attrs:
          is_superuser: false
          users:
            - !Find [authentik_core.user, [username, akadmin]]
      - model: authentik_providers_oauth2.oauth2provider
        id: argocd-provider
        identifiers:
          name: Argo CD production
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: argocd
          client_secret: !Env AUTHENTIK_ARGOCD_PROD_CLIENT_SECRET
          include_claims_in_id_token: true
          issuer_mode: per_provider
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
          redirect_uris:
            - matching_mode: strict
              url: https://argocd.lab.bingo/auth/callback
      - model: authentik_core.application
        identifiers:
          slug: argocd
        attrs:
          name: Argo CD production
          provider: !KeyOf argocd-provider
          meta_launch_url: https://argocd.lab.bingo
      - model: authentik_providers_oauth2.oauth2provider
        id: argocd-test-provider
        identifiers:
          name: Argo CD test
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: argocd-test
          client_secret: !Env AUTHENTIK_ARGOCD_TEST_CLIENT_SECRET
          include_claims_in_id_token: true
          issuer_mode: per_provider
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
          redirect_uris:
            - matching_mode: strict
              url: https://argocd.test.lab.bingo/auth/callback
      - model: authentik_core.application
        identifiers:
          slug: argocd-test
        attrs:
          name: Argo CD test
          provider: !KeyOf argocd-test-provider
          meta_launch_url: https://argocd.test.lab.bingo
