apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: pz-server-secrets
  namespace: pz-server
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: pz-server-secrets
  onlyMappedSecrets: true
  map:
    - bwSecretId: a05d5cd4-7697-4ac6-9ca8-b4dc009cbd38
      secretKeyName: ADMIN_PASSWORD
    - bwSecretId: b35b57f1-9cbb-490b-a73e-b4dc009ce1cb
      secretKeyName: SERVER_PASSWORD
    - bwSecretId: 121eb32b-895a-4b74-b2b7-b4dc009d075a
      secretKeyName: RCON_PASSWORD
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: pz-r2-credentials
  namespace: pz-server
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: pz-r2-credentials
  onlyMappedSecrets: true
  map:
    - bwSecretId: 420f825c-23d8-4161-806d-b4dc00a2f00f
      secretKeyName: AWS_ACCESS_KEY_ID
    - bwSecretId: 8096b9bc-2d66-4f59-925b-b4dc00a30db0
      secretKeyName: AWS_SECRET_ACCESS_KEY
    - bwSecretId: e3b36de4-7f4c-4005-a6b7-b4dc00a39887
      secretKeyName: RESTIC_PASSWORD
  authToken:
    secretName: bw-auth-token
    secretKey: token
