fix:
  - head-branch: ['^fix/']

feature:
  - head-branch: ['^feat/']

documentation:
  - any:
      - head-branch: ['^docs/']
      - changed-files:
          - any-glob-to-any-file:
              - 'docs/**'
              - '**/*.md'

ci:
  - any:
      - head-branch: ['^ci/']
      - changed-files:
          - any-glob-to-any-file: '.github/**'

test:
  - head-branch: ['^test/']

performance:
  - head-branch: ['^perf/']

ansible:
  - changed-files:
      - any-glob-to-any-file: 'ansible/**'

terraform:
  - changed-files:
      - any-glob-to-any-file:
          - 'terraform/**'
          - '**/*.tf'
          - '**/*.tfvars'

kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/**'
          - 'capi/**'
          - 'charts/**'
