fix:
  - any:
      head-branch: ['^fix/.*']

feature:
  - any:
      head-branch: ['^feat/.*']

documentation:
  - any:
      head-branch: ['^docs/.*']

ci:
  - any:
      head-branch: ['^ci/.*']

test:
  - any:
      head-branch: ['^test/.*']

performance:
  - any:
      head-branch: ['^perf/.*']

ansible:
  - any:
      changed-files:
        any-glob-to-any-file:
          - 'ansible/**/*.yml'

terraform:
  - any:
      changed-files:
        any-glob-to-any-file:
          - 'terraform/**/*.tf'
          - 'terraform/**/*.tfvars'

kubernetes:
  - any:
      changed-files:
        any-glob-to-any-file:
          - 'apps/**/*.yaml'
