---

- name: Retrieve helm binary archive.
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Verify extracted helm binary.
  ansible.builtin.stat:
    path: "/tmp/linux-amd64/helm"
  register: helm_binary

- name: Fail if helm binary is not found.
  ansible.builtin.fail:
    msg: "Helm binary not found after extraction"
  when: not helm_binary.stat.exists

- name: Move helm binary into place.
  ansible.builtin.copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    mode: '0755'
    remote_src: true
    force: false
