apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: labprod

patches:
  - target:
      kind: Ingress
      name: portal
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: lab.bingo
      - op: replace
        path: /spec/tls/0/hosts/0
        value: lab.bingo
  - target:
      kind: Deployment
      name: portal
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: labprod
