---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-secret
  namespace: webapps
spec:
  encryptedData:
    credentials.json: AgAVkT0qtbsjCNh4FF798CV8+JiNg2t3KBC55aSGHO2Eju7BNJ0d7Tm9lVNrH6adj+pmA7dKiMVknKfOS43rtAnrXtZX3DYkQPgKzpeZlnFXsWfbHZA7SZkORLJ3uKMtFnAxGIh54Tyg7l24J5KuDGzCXyUee4Lgz3CeXcQU4TDvf4/pZGA2cveKxON62d5CHZn/Balo15ljE+PSv+/ybTCPvkbYwq765qPxL1Cgx7RBqZggeQSN1y2Anc6jsOasVJQ2hhgwM2Dv+XNhDwyiGGWe14W9LzyTSl1/bfOghE5zKXF+I05dzhRcMRkp75l6zoWbW1uukxbZzs30GrdpEd/MowEN1VCH5WyMpXk+Hm/vS4gg8x62JPGK7kn3nBwbftwxoJ7dd4Pwwk0MET4T0pUfeeSUnqGtOo/B8F6z3deNXqnMrCp/oQmjOxFQa0DMzSFnrPR/x7AbUAykFSuIteFN5MQEUEoKtiSDg3BjtZJ+mUSIbgY3jWlxPfuoa7QgDfnivOmdDq0vFyyqUpaAGSj04qGBhatpIcWE0W3JGYNgCPLYwcr0bbJofXjA1ksMGMoC7HRQ144KDrn7tkDDqcsyMK6fPaGGGl1YlvAyChIQCqUNLAkrqTvEoNXWZa7ddc1d5cypIg22FQsgurJAF7aJikWnLT83BwOheQ+SX9m9ZJ1tZii4KBjmmaDnQKwX3ZjUF3u71ywSYEGUDMCJ1UgCEkeeYadN4EiByqR+bSm+3LKwdKuLVaA5NQAR7TNFRTXdacxRxwP5xX6WhQ0SWWGMA3ixK2XZ7FMTFnbFS1S8ti+1EXoe22NN4bUXCjViIyj9UznzsgcUn54EEjhGBQXM42krnb7oNYzQipcKpGv6bQzftYGsb1teGyjuXDDSMq7I+aSwqIKftwmjeeVIn9A8Bt/3gdDnQXoCZoCRBm2+F83IDwc=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-secret
      namespace: webapps
