apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-labtest
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: labops-labtest
  source:
    repoURL: https://github.com/bingops-com/labops.git
    targetRevision: develop
    path: apps/argocd/clusters/labtest
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
