apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barman-cloud-labtest
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: labops-labtest
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.7.0
    helm:
      releaseName: barman-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
