apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - argocd.yaml
  - sealed-secrets.yaml
  - traefik.yaml
  - cert-manager.yaml
  - certificates.yaml
  - private-dns.yaml
  - argocd-access.yaml
