apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-labtest
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: labops-labtest
  source:
    repoURL: https://github.com/bingops-com/labops.git
    targetRevision: master
    path: apps/workloads/portfolio/clusters/labtest
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
