apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-discord
  namespace: monitoring
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: observability-discord
  onlyMappedSecrets: true
  map:
    - bwSecretId: 00000000-0000-0000-0000-000000000201
      secretKeyName: critical-url
    - bwSecretId: 00000000-0000-0000-0000-000000000206
      secretKeyName: infrastructure-url
    - bwSecretId: 00000000-0000-0000-0000-000000000207
      secretKeyName: applications-url
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-grafana
  namespace: monitoring
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: observability-grafana
  onlyMappedSecrets: true
  map:
    - bwSecretId: 00000000-0000-0000-0000-000000000202
      secretKeyName: admin-user
    - bwSecretId: 00000000-0000-0000-0000-000000000203
      secretKeyName: admin-password
    - bwSecretId: 00000000-0000-0000-0000-000000000204
      secretKeyName: elasticsearch-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-elasticsearch-clients
  namespace: logging
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: observability-elasticsearch-clients
  onlyMappedSecrets: true
  map:
    - bwSecretId: 00000000-0000-0000-0000-000000000204
      secretKeyName: grafana-password
    - bwSecretId: 00000000-0000-0000-0000-000000000205
      secretKeyName: fluent-bit-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
