apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-discord
  namespace: monitoring
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: observability-discord
  onlyMappedSecrets: true
  map:
    - bwSecretId: 1f6ed25c-0a3b-4883-b36b-b48f0144b994
      secretKeyName: critical-url
    - bwSecretId: 38194ddf-b925-49d7-8ffa-b48f0144df72
      secretKeyName: infrastructure-url
    - bwSecretId: 261e2138-6d3c-4915-ba8d-b48f0144f8db
      secretKeyName: applications-url
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-grafana-datasource
  namespace: monitoring
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: observability-grafana-datasource
  onlyMappedSecrets: true
  map:
    - bwSecretId: 5c890a30-750f-432c-ac8e-b48f01452f6e
      secretKeyName: elasticsearch-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-elasticsearch-clients
  namespace: logging
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: observability-elasticsearch-clients
  onlyMappedSecrets: true
  map:
    - bwSecretId: 5c890a30-750f-432c-ac8e-b48f01452f6e
      secretKeyName: grafana-password
    - bwSecretId: c2a20803-79df-4831-9d79-b48f014545d9
      secretKeyName: fluent-bit-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
