apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "www.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "www.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "www.name" . }}
    spec:
      containers:
        - name: portfolio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
