apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cnpg-validation-credentials
  namespace: postgresql
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 4ef29235-632e-45c6-a49a-b48f00d8fe6f
  secretName: cnpg-validation-credentials
  onlyMappedSecrets: true
  map:
    - bwSecretId: de5f6a3e-0acb-410a-ac39-b48f00fd4554
      secretKeyName: username
    - bwSecretId: 4a9b3359-6d03-48e5-829f-b48f00fd45e8
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token
