apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database-secret.yaml
  - r2-secret.yaml
  - object-store.yaml
  - cluster.yaml
  - scheduled-backup.yaml
