apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cnpg-r2-credentials
  namespace: postgresql
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 4ef29235-632e-45c6-a49a-b48f00d8fe6f
  secretName: cnpg-r2-credentials
  onlyMappedSecrets: true
  map:
    - bwSecretId: 0ca60613-c9b4-4565-ad34-b48f01006bb9
      secretKeyName: ACCESS_KEY_ID
    - bwSecretId: a41b7cf5-ea24-4e5a-a109-b48f01008349
      secretKeyName: ACCESS_SECRET_KEY
  authToken:
    secretName: bw-auth-token
    secretKey: token
