replicaCount: 1

<<<<<<< HEAD
namespace: bingops
=======
<<<<<<< HEAD
namespace: webapps
>>>>>>> 1f7e53e (fix(www): remove namespace metadata and creation for kustomize)

=======
>>>>>>> 9c8045d (fix(www): remove namespace metadata and creation for kustomize)
fullnameOverride: portfolio

image:
  repository: ghcr.io/bingops-com/www
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: portfolio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
