apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bingops

labels:
  - pairs:
      environment: preprod

resources:
  - ../../../base

helmCharts:
  - name: www
    repo: oci://ghcr.io/bingops-com/helm
    releaseName: www
    namespace: bingops
    version: 0.1.4
    valuesFile: values.yaml
