apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    version: 1.14.0
    releaseName: postgres-operator
    namespace: databases
    valuesFile: values.yaml
