apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: arc-github-app
  namespace: arc-runners
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: arc-github-app
  onlyMappedSecrets: true
  map:
    - bwSecretId: b0c40eb2-9055-456f-ba06-b48f011210c1
      secretKeyName: github_app_id
    - bwSecretId: ceb3562f-98c6-441e-afc3-b48f01126c43
      secretKeyName: github_app_installation_id
    - bwSecretId: 7c7e66ce-d319-4866-a520-b48f01130b5b
      secretKeyName: github_app_private_key
  authToken:
    secretName: bw-auth-token
    secretKey: token
