apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: arc-labtest-kubeconfig
  namespace: arc-runners
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: arc-labtest-kubeconfig
  onlyMappedSecrets: true
  map:
    - bwSecretId: d6bbdc9e-d9d7-4072-a55d-b48f0117960e
      secretKeyName: config
  authToken:
    secretName: bw-auth-token
    secretKey: token
