server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.prod.homelab.local
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    tls: true
