apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: production

helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.30.1
    releaseName: kube-state-metrics
    namespace: monitoring
    valuesFile: values.yaml
