replicaCount: 2

image:
  repository: ghcr.io/bingops-com/www
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: www.bingops.com
      paths:
        - path: /
          pathType: Prefix
    - host: bingops.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
