apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: labprod

patches:
  - target:
      kind: Ingress
      name: glance
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: home.lab.bingo
      - op: replace
        path: /spec/tls/0/hosts/0
        value: home.lab.bingo
