apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
    environment: preprod

helmCharts:
  - name: opencti
    repo: https://devops-ia.github.io/helm-opencti
    version: 1.10.6
    releaseName: opencti
    namespace: opencti
    valuesFile: values.yaml
