apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-private
  namespace: private-dns
data:
  Corefile: |
    argocd.lab.bingo:53 {
        errors
        log
        bind 192.168.10.160
        template IN A {
            match ^argocd[.]lab[.]bingo[.]$
            answer "{{ .Name }} 30 IN A 192.168.10.151"
        }
        cache 30
    }
