apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-access-labprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: labops-labprod
  source:
    repoURL: https://github.com/bingops-com/labops.git
    targetRevision: master
    path: apps/platform/argocd-access/labprod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
