apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-labprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: labops-labprod
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.5.5
    helm:
      valuesObject:
        global:
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: authentik-labprod-postgresql-rw
        authentik:
          existingSecret:
            secretName: authentik-secrets
          postgresql:
            host: authentik-labprod-postgresql-rw
          error_reporting:
            enabled: false
        blueprints:
          configMaps:
            - authentik-blueprints
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-cloudflare
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - auth.lab.bingo
            tls:
              - secretName: authentik-tls
                hosts:
                  - auth.lab.bingo
        postgresql:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
