apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barman-cloud-labprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: labops-labprod
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.7.0
    helm:
      releaseName: barman-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
