apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-secrets-manager-labprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: labops-labprod
  source:
    repoURL: https://charts.bitwarden.com
    chart: sm-operator
    targetRevision: 2.0.3
    helm:
      releaseName: sm-operator
      valuesObject:
        settings:
          bwSecretsManagerRefreshInterval: 300
          cloudRegion: US
  destination:
    server: https://kubernetes.default.svc
    namespace: sm-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
