apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-labprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: labops-labprod
  source:
    repoURL: https://github.com/bingops-com/labops.git
    targetRevision: master
    path: apps/cloudflare/bingops
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
