apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - argocd.yaml
  - bitwarden-secrets-manager.yaml
  - traefik.yaml
  - cert-manager.yaml
  - certificates.yaml
  - local-path-storage.yaml
  - cloudnative-pg.yaml
  - barman-cloud.yaml
  - postgresql.yaml
  - authentik-config.yaml
  - authentik.yaml
  - private-dns.yaml
  - argocd-access.yaml
  - cloudflare-tunnel.yaml
  - portfolio.yaml
