apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-config-labprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: labops-labprod
  source:
    repoURL: https://github.com/bingops-com/labops.git
    targetRevision: master
    path: apps/platform/observability/labprod
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
