apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: romm-labprod
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: labops-labprod
  source:
    repoURL: https://github.com/bingops-com/labops.git
    targetRevision: master
    path: apps/workloads/romm/clusters/labprod
  destination:
    server: https://kubernetes.default.svc
    namespace: romm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
