apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: authentik-cnpg-credentials
  namespace: authentik
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: authentik-cnpg-credentials
  onlyMappedSecrets: true
  map:
    - bwSecretId: 7f327a29-7679-4bd6-b1f3-b48f00fd463a
      secretKeyName: username
    - bwSecretId: 85c73cb5-9032-468a-98f1-b48f00e7e653
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token
