apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: labops-preprod
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Applications managed by GitOps on the preprod cluster
  sourceRepos:
    - https://github.com/bingops-com/labops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
