configs:
  cm:
    admin.enabled: false
    kustomize.buildOptions: --enable-helm
    url: https://argocd.test.lab.bingo
    oidc.config: |
      name: Authentik
      issuer: https://auth.lab.bingo/application/o/argocd-test/
      clientID: argocd-test
      clientSecret: $argocd-oidc:oidc.authentik.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, argocd-admins, role:admin
    scopes: "[groups, email]"
  params:
    server.insecure: true

server:
  ingress:
    enabled: false
