apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - config-init.yaml
  - restore.yaml
  - postgresql.yaml
  - valkey.yaml
  - romm.yaml
  - arr-stack.yaml
  - backup.yaml
