---
- name: Retrieve and Configure kubeconfig for Prod and Preprod
  hosts:
    - preprod
    - production
  remote_user: "{{ new_admin_user }}"
  tasks:
    - name: Fetch kubeconfig file from master node
      ansible.builtin.fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "/tmp/kubeconfig_{{ inventory_hostname }}.yaml"
        flat: true

- name: Setup kubeconfig locally
  hosts: local
  tasks:
    - name: Ensure .kube directory exists in user's home
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Move kubeconfig files dynamically to local .kube directory
      ansible.builtin.copy:
        src: "/tmp/kubeconfig_{{ item }}.yaml"
        dest: "{{ ansible_env.HOME }}/.kube/config_{{ item }}"
        mode: '0644'
      loop: "{{ groups['production'] + groups['preprod'] }}"

    - name: Update server IP in kubeconfig
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.kube/config_{{ item }}"
        regexp: "^\\s*server: https://127.0.0.1:6443"
        line: "    server: https://{{ hostvars[item]['ansible_host'] }}:6443"
      loop: "{{ groups['production'] + groups['preprod'] }}"
      when: hostvars[item]['ansible_host'] is defined
