---

- name: Preprod playbook
  hosts: preprod
  become: true
  remote_user: "{{ new_admin_user }}"
  tags:
    - preprod
    - pp
  roles:
    - ssh
    - node_exporter
    - k3s

- name: Production playbook
  hosts: production
  become: true
  remote_user: "{{ new_admin_user }}"
  tags:
    - production
    - prod
  roles:
    - ssh
    - node_exporter
    - k3s
