apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bingops

labels:
  - pairs:
      environment: production

resources:
  - ../../../base

helmCharts:
  - name: blog
    repo: oci://ghcr.io/bingops-com/helm
    releaseName: blog
    namespace: bingops
    version: 0.1.0
    valuesFile: values.yaml
