apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd-system
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgByIsoe8i07xwhn/7Gy/hGWLv4tUTQdGJRumOPfdL48D+Tkzfr1PHkD8N9D3YoZujfJju6Obe0jwFCWVaN78C9Z/+Af7KwK7JRGwoCQO72ytzzfpK0pbf73QjWpzCHJRrSkgcowGau3L+hIBs7FoZfdFpmYPykfReqwOEB8yCoJ2yAdPEXwnx2ac1pQrZR8BsmPIy7N4w7MS0BflG8ay+t4bS56fHlFhtvNJ3WyToVWXkfP5u/UBh3cQrVtGUNPvqLbg7sU2B7sZ2Cv6oxUveH0aYCHQKqnkeklqI3wsE6Yi5KaGfq8HwJMPljQajoIEWO72mCeA9cegS+dZsiODqs1XOJEh24uW5m2xp/UiEptX/YeZecrmmn2xxiChSPkb4fI6QavlMM6igYVzWiK+XIAdgCwjqjIZDVw6HBboLFPcxkrmec9jYWzKk6gaYQx3OVCJ86YMH58vVQbwMv4wQzBk5vbg1k7etsglj64zr1yxu7CYyzWNzDuaqEc1qJSo4cur6bHbkmgQInykdqPksdU1S0Goj7KAG8HpiTrTqgxpfs3EFsk9nS9jOOdU3SsZPBHvd2WJzpBmUOfxY0M1Y0Kuxk0pmcPUAWc20jpHRuKGT8Kd7fznk4s1MWVM/V1uZ8JRJterGiLOyE+xNCMv+qihPgcYdICB/1v8Nb/hZ7PhjQSOC7j2yId7p3hys8j41pZTju9g5xzhIJq37fBB4iW0sJYqJlcILVFCqb8OTgeyHwyqiyz5UFeOq91Xyelf856yBmaVJ2CEHYYc7YrXrK7
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd-system
    type: Opaque
