apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: argocd-oidc
  namespace: argocd-system
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: argocd-oidc
  onlyMappedSecrets: true
  map:
    - bwSecretId: 21b0207b-70d0-4f6d-a4e7-b48f00e7e2d8
      secretKeyName: oidc.authentik.clientSecret
  authToken:
    secretName: bw-auth-token
    secretKey: token
