apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-discord
  namespace: monitoring
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 4ef29235-632e-45c6-a49a-b48f00d8fe6f
  secretName: observability-discord
  onlyMappedSecrets: true
  map:
    - bwSecretId: ad72df54-9398-42af-9bdb-b48f014566aa
      secretKeyName: critical-url
    - bwSecretId: 8078c8a6-8f05-4379-89b9-b48f01458d65
      secretKeyName: infrastructure-url
    - bwSecretId: 25d70300-78cc-40db-851d-b48f0145b1ff
      secretKeyName: applications-url
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-grafana-datasource
  namespace: monitoring
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 4ef29235-632e-45c6-a49a-b48f00d8fe6f
  secretName: observability-grafana-datasource
  onlyMappedSecrets: true
  map:
    - bwSecretId: fc2c2933-2943-438f-9d13-b48f0146187a
      secretKeyName: elasticsearch-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: observability-elasticsearch-clients
  namespace: logging
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 4ef29235-632e-45c6-a49a-b48f00d8fe6f
  secretName: observability-elasticsearch-clients
  onlyMappedSecrets: true
  map:
    - bwSecretId: fc2c2933-2943-438f-9d13-b48f0146187a
      secretKeyName: grafana-password
    - bwSecretId: 8fa1fcff-383b-4eb5-a8c7-b48f01462aed
      secretKeyName: fluent-bit-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
