apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: observability
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  # renovate: datasource=docker depName=docker.elastic.co/elasticsearch/elasticsearch
  version: 9.4.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms384m -Xmx384m
              resources:
                requests:
                  cpu: 100m
                  memory: 768Mi
                limits:
                  cpu: 750m
                  memory: 1Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: local-path
