apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespaces.yaml
  - bitwarden-secrets.yaml
  - elasticsearch.yaml
  - elasticsearch-bootstrap.yaml
  - grafana-allowlist.yaml
