apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      environment: production

resources:
  - ../../../base

helmCharts:
  - name: www
    repo: oci://ghcr.io/bingops-com/helm
    releaseName: www
    namespace: webapps
    version: 0.1.2
    valuesFile: values.yaml
