apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status.fullname" . }}-config
  labels:
    {{- include "status.labels" . | nindent 4 }}
data:
  status.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
