apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: preprod

helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.30.1
    releaseName: kube-state-metrics
    namespace: monitoring
    valuesFile: values.yaml

patches:
  - target:
      kind: Ingress
      name: kube-metrics-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kube-metrics.preprod.homelab.local
