apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd-system
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgAzjD5KB3cW+HVz5vZMO8nbwcBzlQv4/51BbTug5WSZugksozg+8QcpcIhp5RjKZI6hyCrAvJsVHQeTbs8Tnj0lCvjZZxyn5bddFQNy4M+iR7UPO0aXcge+wIXuEzETslv7frx9aStJ3LW18lbvxlgZi/3vLe2g63UA9+ocDpcvSGkPow57x8BTW34tQI5TY4jUilaWyi/BgMR3sueqPFqBDpsYMXr6GL4FghK5GsxPWpEnZaZxds+iyFG1jqpYmBRdT7Z20xcD/6OLH0Eywjh4fjjxhI5PP4gb0ZgZa0MBTVRVB9evsXrj2S1BPZN6ejf8LQBU7xLJxABJHlKZlm32l1pYUvJ/KSaKyrY0zKGBWJRZrLU2YiMTeUlTzrESrhwUCo0569FVJDH1aqaXHyloc/xlfNVVQhxHXY+iAN8OM5DHgx2WY/k03o1+j3WX7lN5tW8ZEhNGf3zC3Ym43iksCYuP1QRkzwQ3U2S+YV/Amj077S/PACZCCxnfIqg36uNmF3gAxeBgxigPKyU16XAtsHYSahs5sw2Qc0nW6zOvaeJyqdCDW5B6op0DsKDKXav3nOD3E/d+MWsH3SIvyBqav3zwILMDt/QIC9s4unY+1FVe9K4UlMo1IXx5criEvuYLrR+2f6JsTPel37nX9SI6UxaGWk73+lHHImde7Ww7UYeyyt1MeMVg17HxlGN/wWNL/aM9eGc/CuNw0JBHJ8hZi2rv5LxJoFXVpXQIPkBUCJa1iLZTl6sT1Acf0aegTHPPFkMmkOAAW8qZRxoZJ8AL
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd-system
    type: Opaque
