apiVersion: v1
kind: ServiceAccount
metadata:
  name: labtest-pr-deployer
  namespace: argocd-system
---
apiVersion: v1
kind: Secret
metadata:
  name: labtest-pr-deployer-token
  namespace: argocd-system
  annotations:
    kubernetes.io/service-account.name: labtest-pr-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: labtest-pr-deployer
  namespace: argocd-system
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labtest-pr-deployer
  namespace: argocd-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: labtest-pr-deployer
subjects:
  - kind: ServiceAccount
    name: labtest-pr-deployer
    namespace: argocd-system
