---
name: ansible-lint
on:
  push:
    branches:
      - master
    paths:
      - 'ansible/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'ansible/**'

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          path: "./ansible"
