name: Build and Push Docker image to GHCR

on:
  repository_dispatch:
    types: [rebuild-image]

  push:
    branches:
      - master
    paths:
      - 'docker/**'

  pull_request:
    branches:
      - master
    paths:
      - 'docker/**'

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "*Dockerfile"
          recursive: true

  get-modified-images:
    needs: hadolint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of modified docker contexts
        id: set-matrix
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.event.client_payload.image }}
          IS_PR: ${{ github.event.client_payload.is_pr }}
        run: bash .github/scripts/get-modified-images.sh

  build-push:
    needs: get-modified-images
    if: ${{ fromJson(needs.get-modified-images.outputs.matrix).include != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-modified-images.outputs.matrix) }}
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: ${{ matrix.image }}
      BUILD_CONTEXT: docker/${{ matrix.image }}
      DOCKERFILE_PATH: docker/${{ matrix.image }}/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate input
        run: bash .github/scripts/validate-input.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: bingops
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Determine tag prefix
        id: tagprefix
        run: bash .github/scripts/determine-tag-prefix.sh
        env:
          IS_PR: ${{ matrix.is_pr }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bingops-com/${{ env.IMAGE_NAME }}
          tags: |
            ${{ matrix.is_pr != 'true' && 'type=raw,value=latest' || '' }}
            type=sha
            type=raw,value=${{ steps.tagprefix.outputs.prefix }}{{date 'YYYYMMDD-HHmmss'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
