name: Build and Push Docker image to GHCR

on:
  repository_dispatch:
    types: [rebuild-image]

  push:
    branches:
      - master
    paths:
      - 'docker/www/**'
      - 'docker/blog/**'

  pull_request:
    branches:
      - main
    paths:
      - 'docker/www/**'
      - 'docker/blog/**'

jobs:
  hadolint:
    runs-on: ubuntu-latest

    container:
      image: hadolint/hadolint:v2.12.0
      options: --entrypoint ""  # pour éviter que l'image force l'entrée standard

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Hadolint on all Dockerfiles
        run: |
          find docker/** -name Dockerfile -print0 | xargs -0 -n1 hadolint
  build-push:
    needs: hadolint
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ${{ github.event.client_payload.image }}
      BUILD_CONTEXT: docker/${{ github.event.client_payload.image }}
      DOCKERFILE_PATH: docker/${{ github.event.client_payload.image }}/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: bingops
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bingops-com/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
