name: terraform-lint

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  terraform-lint:
    name: Terraform Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache TFLint plugin directory
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ runner.os }}-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Show TFLint version
        run: tflint --version

      - name: Run TFLint in all terraform subdirectories
        run: |
          find terraform -type f -name "*.tf" -exec dirname {} \; | sort -u | while read dir; do
            echo "Running TFLint in $dir"
            tflint --init --chdir="$dir"
            tflint -f compact --chdir="$dir"
          done
        env:
          GITHUB_TOKEN: ${{ github.token }}
