apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  organizationId: 38fd86e7-06ee-4ee3-b013-b48f00d76a9e
  projectId: 113f6039-1da2-4f51-aa24-b48f00d909de
  secretName: cloudflare-api-token
  onlyMappedSecrets: true
  map:
    - bwSecretId: ea9e6b51-6426-40f3-8974-b48f00e7e379
      secretKeyName: api-token
  authToken:
    secretName: bw-auth-token
    secretKey: token
